# 项目：评估和清理英国电商公司销售数据

## 分析目标

此数据分析的目的是，根据市场销售数据，挖掘畅销产品，以便制定更有效的市场策略来提升营收。

本实战项目的目的在于练习评估数据干净和整洁度，并且基于评估结果，对数据进行清洗，从而得到可供下一步分析的数据。

## 简介

原始数据集记录了一家英国在线零售公司在2010年12月1日至2011年12月9日期间的所有交易情况，涵盖了该公司在全球不同国家和地区的业务数据。该公司主要销售覆盖各个场景的礼品，包括但不限于生日礼品、结婚纪念品、圣诞礼品等等。该公司的客户群体主要包括批发商和个人消费者，其中批发商占据了相当大的比例。

数据每列的含义如下：
- `InvoiceNo`: 发票号码。6位数，作为交易的唯一标识符。如果这个代码以字母“c”开头，表示这笔交易被取消。
- `StockCode`: 产品代码。5位数，作为产品的唯一标识符。
- `Description`: 产品名称。
- `Quantity`: 产品在交易中的数量。
- `InvoiceDate`: 发票日期和时间。交易发生的日期和时间。
- `UnitPrice`: 单价。价格单位为英镑（£）。
- `CustomerID`: 客户编号。5位数，作为客户的唯一标识符。
- `Country`: 国家名称。客户所居住的国家的名称。

## 读取数据

In [1]:
import pandas as pd

In [2]:
original_data=pd.read_csv("e_commerce.csv")

In [3]:
original_data.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

评估数据整齐度

In [4]:
original_data.sample(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
436919,574250,84927F,PSYCHEDELIC TILE HOOK,6,11/3/2011 13:09,0.39,17634.0,United Kingdom
278139,561209,21716,BOYS VINTAGE TIN SEASIDE BUCKET,1,7/25/2011 16:57,2.46,NaN,United Kingdom
420352,572887,22892,SET OF SALT AND PEPPER TOADSTOOLS,12,10/26/2011 13:47,1.25,12362.0,Belgium
16487,537666,22425,ENAMEL COLANDER CREAM,1,12/7/2010 18:36,10.17,NaN,United Kingdom
330478,565919,22196,SMALL HEART MEASURING SPOONS,1,9/7/2011 16:48,1.63,NaN,United Kingdom
303611,563549,22385,JUMBO BAG SPACEBOY DESIGN,3,8/17/2011 12:34,4.13,NaN,United Kingdom
498809,578541,21672,WHITE SPOT RED CERAMIC DRAWER KNOB,6,11/24/2011 15:01,1.45,14277.0,France
120103,546648,20719,WOODLAND CHARLOTTE BAG,43,3/15/2011 14:15,2.46,NaN,United Kingdom
517616,580066,22556,PLASTERS IN TIN CIRCUS PARADE,12,12/1/2011 13:33,1.65,14309.0,United Kingdom
248006,558777,22699,ROSES REGENCY TEACUP AND SAUCER,3,7/4/2011 10:23,5.79,NaN,United Kingdom

评估数据干净度

In [5]:
original_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

1.InvoiceDate数据类型应为日期型
2.CustomerID数据应为字符串型且数据缺失严重
3.Description数据缺失

In [6]:
original_data["InvoiceDate"]=pd.to_datetime(original_data["InvoiceDate"])
original_data["InvoiceDate"]

0        2010-12-01 08:26:00
1        2010-12-01 08:26:00
2        2010-12-01 08:26:00
3        2010-12-01 08:26:00
4        2010-12-01 08:26:00
                 ...
541904   2011-12-09 12:50:00
541905   2011-12-09 12:50:00
541906   2011-12-09 12:50:00
541907   2011-12-09 12:50:00
541908   2011-12-09 12:50:00
Name: InvoiceDate, Length: 541909, dtype: datetime64[ns]

In [7]:
original_data["CustomerID"]=original_data["CustomerID"].astype(str)
original_data["CustomerID"]

0         17850.0
1         17850.0
2         17850.0
3         17850.0
4         17850.0
           ...
541904    12680.0
541905    12680.0
541906    12680.0
541907    12680.0
541908    12680.0
Name: CustomerID, Length: 541909, dtype: object

In [8]:
original_data[original_data["CustomerID"].isnull()]

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country]
Index: []

In [9]:
original_data[original_data["Description"].isnull()]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.0,nan,United Kingdom
1970,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,nan,United Kingdom
1971,536546,22145,NaN,1,2010-12-01 14:33:00,0.0,nan,United Kingdom
1972,536547,37509,NaN,1,2010-12-01 14:33:00,0.0,nan,United Kingdom
1987,536549,85226A,NaN,1,2010-12-01 14:34:00,0.0,nan,United Kingdom
...,...,...,...,...,...,...,...,...
535322,581199,84581,NaN,-2,2011-12-07 18:26:00,0.0,nan,United Kingdom
535326,581203,23406,NaN,15,2011-12-07 18:31:00,0.0,nan,United Kingdom
535332,581209,21620,NaN,6,2011-12-07 18:35:00,0.0,nan,United Kingdom
536981,581234,72817,NaN,27,2011-12-08 10:33:00,0.0,nan,United Kingdom
538554,581408,85175,NaN,20,2011-12-08 14:06:00,0.0,nan,United Kingdom

In [10]:
original_data[(original_data["Description"].isnull())&(original_data["UnitPrice"]!=0)]

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country]
Index: []

In [11]:
original_data=original_data.dropna(subset=["Description"])
original_data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [12]:
original_data["Description"].isnull().sum()

np.int64(0)

In [13]:
original_data["CustomerID"].isnull().sum()

np.int64(0)

In [14]:
original_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 540455 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    540455 non-null  object
 1   StockCode    540455 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     540455 non-null  int64
 4   InvoiceDate  540455 non-null  datetime64[ns]
 5   UnitPrice    540455 non-null  float64
 6   CustomerID   540455 non-null  object
 7   Country      540455 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(1), object(5)
memory usage: 37.1+ MB

In [15]:
original_data["CustomerID"]

0         17850.0
1         17850.0
2         17850.0
3         17850.0
4         17850.0
           ...
541904    12680.0
541905    12680.0
541906    12680.0
541907    12680.0
541908    12680.0
Name: CustomerID, Length: 540455, dtype: object

In [16]:
original_data["CustomerID"]=original_data["CustomerID"].str.replace(".0","")
original_data["CustomerID"]

0         17850
1         17850
2         17850
3         17850
4         17850
          ...
541904    12680
541905    12680
541906    12680
541907    12680
541908    12680
Name: CustomerID, Length: 540455, dtype: object

In [17]:
original_data["Country"].value_counts()

Country
United Kingdom          493812
Germany                   9495
France                    8557
EIRE                      8196
Spain                     2533
Netherlands               2371
Belgium                   2069
Switzerland               2002
Portugal                  1519
Australia                 1259
Norway                    1086
Italy                      803
Channel Islands            758
Finland                    695
Cyprus                     622
Sweden                     462
Unspecified                446
Austria                    401
Denmark                    389
Japan                      358
Poland                     341
Israel                     297
China                      288
Singapore                  229
USA                        218
UK                         211
Iceland                    182
Canada                     151
Greece                     146
Malta                      127
United States               73
United Arab Emirates        68
European Community          61
RSA                         58
Lebanon                     45
Lithuania                   35
Brazil                      32
Czech Republic              30
Bahrain                     19
Saudi Arabia                10
U.K.                         1
Name: count, dtype: int64

In [18]:
original_data["Country"]=original_data["Country"].replace(["U.K.","UK"],"United Kingdom")
original_data["Country"]=original_data["Country"].replace("USA.","United States")

In [19]:
original_data.describe()

            Quantity                    InvoiceDate      UnitPrice
count  540455.000000                         540455  540455.000000
mean        9.603129  2011-07-04 16:20:42.947035392       4.623519
min    -80995.000000            2010-12-01 08:26:00  -11062.060000
25%         1.000000            2011-03-28 11:49:00       1.250000
50%         3.000000            2011-07-20 11:38:00       2.080000
75%        10.000000            2011-10-19 11:49:00       4.130000
max     80995.000000            2011-12-09 12:50:00   38970.000000
std       218.007598                            NaN      96.889628

In [20]:
original_data["Quantity"]<0

0         False
1         False
2         False
3         False
4         False
          ...
541904    False
541905    False
541906    False
541907    False
541908    False
Name: Quantity, Length: 540455, dtype: bool

In [21]:
print(original_data.shape)

(540455, 8)

In [23]:
 original_data= original_data[original_data["Quantity"] >= 0]

In [24]:
len(original_data[original_data["Quantity"] < 0])

0

In [25]:
 original_data= original_data[original_data["UnitPrice"] >= 0]

In [26]:
len(original_data[original_data["UnitPrice"] < 0])

0

In [27]:
original_data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680,France

In [28]:
original_data.describe()

            Quantity                    InvoiceDate      UnitPrice
count  530691.000000                         530691  530691.000000
mean       10.605855  2011-07-04 19:01:11.249597440       3.903303
min         1.000000            2010-12-01 08:26:00       0.000000
25%         1.000000            2011-03-28 11:59:00       1.250000
50%         3.000000            2011-07-20 12:14:00       2.080000
75%        10.000000            2011-10-19 12:35:00       4.130000
max     80995.000000            2011-12-09 12:50:00   13541.330000
std       156.638147                            NaN      35.896047

In [29]:
original_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 530691 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    530691 non-null  object
 1   StockCode    530691 non-null  object
 2   Description  530691 non-null  object
 3   Quantity     530691 non-null  int64
 4   InvoiceDate  530691 non-null  datetime64[ns]
 5   UnitPrice    530691 non-null  float64
 6   CustomerID   530691 non-null  object
 7   Country      530691 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(1), object(5)
memory usage: 36.4+ MB

## 评估数据

## 清理数据

## 保存清理后的数据